---
# leaf2 — AS 65002, Loopback0 10.0.0.2
bgp_asn: 65002
loopback_ip: 10.0.0.2

fabric_links:
  - interface: Ethernet1
    description: spine1-Eth2
    local_ip: 10.1.0.3/31
    remote_ip: 10.1.0.2
    remote_asn: 65000
  - interface: Ethernet2
    description: spine2-Eth2
    local_ip: 10.1.0.11/31
    remote_ip: 10.1.0.10
    remote_asn: 65005
